name: news60
description: A news app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  webview_flutter:
  photo_view:
  cached_network_image: ^3.1.0
  transformer_page_view: ^0.1.6
  provider:
  dio: ^4.0.0
  http: ^0.13.3
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  json_annotation:
  equatable: ^2.0.3
  news360_api:
    path: packages/news360_api
  screenshot: ^1.2.3
  image_gallery_saver:
  permission_handler:
  share_plus: ^2.1.4
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  responsive_framework: ^0.1.4
  flutter_udid: ^2.0.0
  cron: ^0.3.2
  fluttertoast: ^8.0.8
  double_back_to_close_app: ^2.0.1
  shimmer: ^2.0.0
  timeago: ^3.1.0
  video_player: ^2.2.7
  youtube_player_flutter: ^8.0.0
dependency_overrides:
  path_provider: 2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  hive_generator: ^1.0.1
  json_serializable:
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gif/
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
